<?php
/**
 * AttemptTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Smartcalls
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* SmartCalls IO API Documentation
 *
* <h1>Basic description</h1> <p>HTTP API is available via the <u>https://smartcalls.io/api/v2/<b>{method}</b></u> endpoint. To use the methods marked with the LOCK symbol, you need to generate an access_token via the <b>getAccessToken</b> method. Pass this access token to each HTTP API call.</p> <h1>Authentication</h1> <p>This API uses Custom Query Parameter for its authentication.</p> <p>The parameters that are needed to be sent for this type of authentication are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
* OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.2
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Smartcalls;

/**
 * AttemptTypeTest Class Doc Comment
 *
 * @category    Class
 * @description AttemptType
 * @package     Smartcalls
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AttemptTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AttemptType"
     */
    public function testAttemptType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "calllist_item_id"
     */
    public function testPropertyCalllistItemId()
    {
    }

    /**
     * Test attribute "datetime_start"
     */
    public function testPropertyDatetimeStart()
    {
    }

    /**
     * Test attribute "datetime_end"
     */
    public function testPropertyDatetimeEnd()
    {
    }

    /**
     * Test attribute "attempt_num"
     */
    public function testPropertyAttemptNum()
    {
    }

    /**
     * Test attribute "record_url"
     */
    public function testPropertyRecordUrl()
    {
    }

    /**
     * Test attribute "attempt_status"
     */
    public function testPropertyAttemptStatus()
    {
    }

    /**
     * Test attribute "call_data"
     */
    public function testPropertyCallData()
    {
    }

    /**
     * Test attribute "attempt_cost"
     */
    public function testPropertyAttemptCost()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "recalc"
     */
    public function testPropertyRecalc()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "call_result_code"
     */
    public function testPropertyCallResultCode()
    {
    }

    /**
     * Test attribute "call_resources"
     */
    public function testPropertyCallResources()
    {
    }
}
