<?php
/**
 * NotificationTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Smartcalls
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* SmartCalls IO API Documentation
 *
* <h1>Basic description</h1> <p>HTTP API is available via the <u>https://smartcalls.io/api/v2/<b>{method}</b></u> endpoint. To use the methods marked with the LOCK symbol, you need to generate an access_token via the <b>getAccessToken</b> method. Pass this access token to each HTTP API call.</p> <h1>Authentication</h1> <p>This API uses Custom Query Parameter for its authentication.</p> <p>The parameters that are needed to be sent for this type of authentication are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
* OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.2
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Smartcalls;

/**
 * NotificationTypeTest Class Doc Comment
 *
 * @category    Class
 * @description NotificationType
 * @package     Smartcalls
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotificationTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NotificationType"
     */
    public function testNotificationType()
    {
    }

    /**
     * Test attribute "min_balance"
     */
    public function testPropertyMinBalance()
    {
    }

    /**
     * Test attribute "status_balance"
     */
    public function testPropertyStatusBalance()
    {
    }

    /**
     * Test attribute "participants1"
     */
    public function testPropertyParticipants1()
    {
    }

    /**
     * Test attribute "campaign_end"
     */
    public function testPropertyCampaignEnd()
    {
    }

    /**
     * Test attribute "status_campaign_end"
     */
    public function testPropertyStatusCampaignEnd()
    {
    }

    /**
     * Test attribute "participants2"
     */
    public function testPropertyParticipants2()
    {
    }

    /**
     * Test attribute "subscription_is_frozen"
     */
    public function testPropertySubscriptionIsFrozen()
    {
    }

    /**
     * Test attribute "status_subscription_is_frozen"
     */
    public function testPropertyStatusSubscriptionIsFrozen()
    {
    }

    /**
     * Test attribute "participants3"
     */
    public function testPropertyParticipants3()
    {
    }

    /**
     * Test attribute "account_document_uploaded"
     */
    public function testPropertyAccountDocumentUploaded()
    {
    }

    /**
     * Test attribute "status_account_document_uploaded"
     */
    public function testPropertyStatusAccountDocumentUploaded()
    {
    }

    /**
     * Test attribute "participants4"
     */
    public function testPropertyParticipants4()
    {
    }
}
