<?php
/**
 * PhoneNumberTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Smartcalls
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* SmartCalls IO API Documentation
 *
* <h1>Basic description</h1> <p>HTTP API is available via the <u>https://smartcalls.io/api/v2/<b>{method}</b></u> endpoint. To use the methods marked with the LOCK symbol, you need to generate an access_token via the <b>getAccessToken</b> method. Pass this access token to each HTTP API call.</p> <h1>Authentication</h1> <p>This API uses Custom Query Parameter for its authentication.</p> <p>The parameters that are needed to be sent for this type of authentication are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
* OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.2
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Smartcalls;

/**
 * PhoneNumberTypeTest Class Doc Comment
 *
 * @category    Class
 * @description PhoneNumberType
 * @package     Smartcalls
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PhoneNumberTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PhoneNumberType"
     */
    public function testPhoneNumberType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "domain_id"
     */
    public function testPropertyDomainId()
    {
    }

    /**
     * Test attribute "auto_charge"
     */
    public function testPropertyAutoCharge()
    {
    }

    /**
     * Test attribute "can_be_used"
     */
    public function testPropertyCanBeUsed()
    {
    }

    /**
     * Test attribute "category_name"
     */
    public function testPropertyCategoryName()
    {
    }

    /**
     * Test attribute "phone_country_code"
     */
    public function testPropertyPhoneCountryCode()
    {
    }

    /**
     * Test attribute "phone_purchase_date"
     */
    public function testPropertyPhonePurchaseDate()
    {
    }

    /**
     * Test attribute "required_verification"
     */
    public function testPropertyRequiredVerification()
    {
    }

    /**
     * Test attribute "verification_status"
     */
    public function testPropertyVerificationStatus()
    {
    }

    /**
     * Test attribute "deactivated"
     */
    public function testPropertyDeactivated()
    {
    }

    /**
     * Test attribute "unverified_hold_until"
     */
    public function testPropertyUnverifiedHoldUntil()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "phone_next_renewal"
     */
    public function testPropertyPhoneNextRenewal()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "phone_price"
     */
    public function testPropertyPhonePrice()
    {
    }

    /**
     * Test attribute "phone_region_id"
     */
    public function testPropertyPhoneRegionId()
    {
    }

    /**
     * Test attribute "redirect_number"
     */
    public function testPropertyRedirectNumber()
    {
    }
}
